### ISSUE TITLE
where is the directory apache2 comming from

### ISSUE THREAD

**Issue by SubOptimal** [rimelek/httpd24-docker-image#1]
The line `COPY apache2 /usr/local/apache2` fails. Where the directory is supposed to come from?

**Comment by SubOptimal** [comment]
Sorry my fault. I took only the Dockerfile from Docker Hub. PEBKAC.

**Comment by rimelek** [comment]
@SubOptimal Yes, you need to clone the whole project if you want to build a custom image. Keep in mind this is a deprecated repository and has moved to https://github.com/itsziget/httpd24-docker-image 

You can clone, customize and build a custom image, however, I recommend you to pull the built image from Docker Hub (https://hub.docker.com/r/itsziget/httpd24/) and use that as parent image.

Documentation: https://httpd24-docker-image.readthedocs.io/en/latest/
