### ISSUE TITLE
Change the value of AuthType for security?

### ISSUE THREAD

**Issue by huanghc** [rimelek/httpd24-docker-image#1]
In the [config file](https://github.com/itsziget/httpd24-docker-image/blob/480e28ceb9b19151495d0922ccf52e73d64c080a/apache2/conf/custom-extra/httpauth.conf), **AuthType** is set to **Basic**, which uses HTTP Basic Authentication to restrict access by looking up users in the given providers.

However, the Httpd [official document](https://httpd.apache.org/docs/2.4/mod/mod_dav.html#security) recommends to set **AuthType** to at least "Digest". 
"The use of HTTP Basic Authentication is not recommended. You should use at least HTTP Digest Authentication, which is provided by the mod_auth_digest module." 

I wonder if the value of this parameter need to be changed for security concern. Thanks.

**Comment by rimelek** [comment]
@huanghc Thank you for your comment. I am happy to read any advice or question that helps me improve the image. The official documentation of httpd says more about it, however. As you can read on the page you linked

> An alternative is Basic Authentication over an SSL enabled connection

Your quoted text is about webdav. If you check the documentation of [Auth Digest](http://httpd.apache.org/docs/current/mod/mod_auth_digest.html) you will see this:

>  However, this does not lead to a significant security advantage over basic authentication. On the other hand, the password storage on the server is much less secure with digest authentication than with basic authentication. **Therefore, using basic auth and encrypting the whole connection using mod_ssl is a much better alternative.**

My goal was to support SSL and one authentication method mainly for testing purposes. In production I think it is better to use an own configuration file mounted into the container or copied into a new image based on this.

Of course if you don't need more than a simple authentication only for a few users, you can use the built in method and create a [free SSL certificate](https://certbot.eff.org/). Let's Encrypt is what I use for my websites.

There are many [dockerized solutions](https://hub.docker.com/search?q=letsencrypt&type=image) to automate it. Here is mine: [itsziget/letsencrypt-http](https://hub.docker.com/r/itsziget/letsencrypt-http) but it definitely needs more attention from me, so it may not be the best choice at this moment :)

**Comment by huanghc** [comment]
@rimelek Thank you for your detailed explanation!
