### ISSUE TITLE
Question about ServerName and ServerAdmin?

### ISSUE THREAD

**Issue by odunybrad** [rimelek/httpd24-docker-image#3]
Thanks for providing the container! 

I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerName` is set to `dummy-host.example.com` in `/usr/local/apache2/conf/original/extra/httpd-vhosts.conf` and `ServerAdmin` is set to `you@example.com` in `usr/local/apache2/conf/original/httpd.conf`.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends the following config:
*  `ServerName` : "For optimal reliability and predictability, you should specify an explicit hostname and port using the ServerName directive."
*  `ServerAdmin`: "However, it's recommended to actually use an email address, since there are a lot of CGI scripts that make that assumption. "

Could you please provide a knob to specify the value of `ServerName` and `ServerAdmin` to identify yourself?

**Comment by rimelek** [comment]
Hi. Both of the directives has a variable to change the value as you can see [in the documentation](https://httpd24-docker-image.readthedocs.io/en/latest/variables.html#variables)

But it doesn't really matter what the value of ServerName unless you need HTTPS. In that case the ServerName must be in the certificate. The official documentation talks about virtual hosts. Docker containers does not usually use virtual hosts but a load balancer/reverse proxy that knows which hostname belongs to which container. So without HTTPS the ServerName is irrelevant.

In fact when you have a trusted local network the reverse proxy can handle the SSL certificates and use HTTP to forward the request to the container.
